version: '3'

      

services:
  groupmanager-database:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=group_manager
    ports:
      - "3307:3306"
    volumes:
       - mysql-room:/var/lib/mysql
  group-information:
    image: group_manager.jar
    ports:
      - "9999:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://groupmanager-database:3306/group_manager
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - groupmanager-database
      
volumes:
  mysql-room:

    
